### ISSUE TITLE
tinderAutolike.rb:81:in `<main>': undefined method `split' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by Nicolas-vrcc** [tarraschk/TinderAutoLike#16]
I got the script running 1 time with a regular account and it worked fine. Then I tried with a premium one and I got this error.
My creditals are correct and I have checked everything
tinderAutolike.rb:81:in `<main>': undefined method `split' for nil:NilClass (NoMethodError)

**Comment by tarraschk** [comment]
Hello,

Can you try to launch again the script?

Basically, the issue here is that the script was not able to parse the URL given by Facebook with the "auth_token" that we need to identify on Tinder.

The cause can be slow network, or a browser working too fast for the script.

Could you describe what happen in your browser when we try to fetch the token please?

**Comment by tarraschk** [comment]
By any chance, can you also check that the account has already been used before to connect on Tinder?

For instance, can you log in the Facebook account you want to use, and try to connect to the following URL:
https://www.facebook.com/v2.6/dialog/oauth?redirect_uri=fb464891386855067%3A%2F%2Fauthorize%2F&scope=user_birthday,user_photos,user_education_history,email,user_relationship_details,user_friends,user_work_history,user_likes&response_type=token%2Csigned_request&client_id=464891386855067

**Comment by tarraschk** [comment]
Hey @Nicolas-vrcc, any update?
