### ISSUE TITLE
TinderAutoLike.rb:68:in `<main>': undefined method `captures' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by tr33m4n** [tarraschk/TinderAutoLike#4]
Hello there,

Tried running your script but it stopped at line 68 with

`TinderAutoLike.rb:68:in `<main>': undefined method `captures' for nil:NilClass (NoMethodError)`

Any ideas?
Cheers

**Comment by tarraschk** [comment]
Hi there,

so it seems it did not fetch correctly your fb_token.

How did you run the script? Did you follow the README? Did you use bundler as expected?

Also, did the script properly open a window?

**Comment by tr33m4n** [comment]
Hi again,

Yes I followed your README exactly and it installed all dependencies correctly. I'm running Ubuntu 14.10 with ruby 2.1.2p95. Strangely it opens Firefox rather than my default browser Chromium, however I'd imagine that might be an issue with defaults on my system, not your script.

It did open a window, however below the "Success" text there was "SECURITY WARNING: Please treat the URL above as you would your password and do not share it with anyone. See the Facebook Help Centre for more information." and the browser does not close, then the error mentioned above happens

**Comment by tarraschk** [comment]
Could you try it with Ruby 1.9.3-p545?
That is the version with which I run the script.

**Comment by tr33m4n** [comment]
Same issue with Ruby 1.9.3-p551 (Could not get hold of p545)

**Comment by tarraschk** [comment]
Did you change properly lines 24 and 25:
```
myLogin = 'YOUR_FACEBOOK_EMAIL_ADDRESS'
myPassword = 'YOUR_FACEBOOK_PASSWORD'
```

You must change those lines so that my script can access your FB_Token.
Do not worry, the login and password information only are exchanged between your computer and facebook servers.

If you already changed that, have you already use Tinder before on your mobile phone?

I just tried again my script and everything worked well on my side :(

**Comment by tr33m4n** [comment]
Yes to every question. I do not know what is wrong :S Maybe Facebook has rolled out a modification to how it sends tokens that hasn't propagated your way yet.

**Comment by tarraschk** [comment]
I only have one last idea to unlock your case.

Actually, line 62 is asking you to fetch a token.
In order to do so, you must be logged in, which is why you have to configure properly the bot on lines 24 and 25.

When the bot puts your login, your password, and then click on "login", it immediately redirect you on another URL with something named "access_token" in it.

My bot is actually catching this URL and parsing it.
In your case, this step if failing and we don't know why.

=> May you copy/paste here the URL on which you are redirected?

Be careful: this URL appears just for a few seconds and immediately changes again. That is why my bot is very useful, as it is easier for him to catch it than for a human.

Also, please replace the token part by something like XXX, to keep your token confidential.

I just want to see what your URL is looking like, so I can improve the Regular Expression which is parsing it, and finally solve your problem.

**Comment by tr33m4n** [comment]
It may have something to do with Facebook asking me to "add a new browser" to my allowed browser list, which happens every time I run this script

**Comment by tarraschk** [comment]
I have never encountered this issue...
This problem should be treated just before line 68: https://github.com/tarraschk/TinderAutoLike/blob/master/TinderAutoLike.rb#L68

If you are asked this question, my script is not detecting that and is trying to fetch your FB_TOKEN.

=> Could you make Facebook remember your browser?

Otherwise I can either work on the issue if you give me some screenshots (dont put sensitive information), or you can fork the project to handle the issue.

**Comment by DannyAdmedo** [comment]
I ran in to this error; Facebook had suspended my account for a login from an unknown source. I was using my box in the netherlands; after confirming it was me it worked as normal.

**Comment by tarraschk** [comment]
Perfect :+1:
